-- 먼저 기존 테이블을 삭제
DROP TABLE IF EXISTS Shared_Story_Replies;
DROP TABLE IF EXISTS Shared_Stories;
DROP TABLE IF EXISTS Used_Kanjis;
DROP TABLE IF EXISTS Community_Replies;
DROP TABLE IF EXISTS Kanji_Collections;
DROP TABLE IF EXISTS Community_Posts;
DROP TABLE IF EXISTS Stories;
DROP TABLE IF EXISTS Kanjis;
DROP TABLE IF EXISTS Users;


-- Users 테이블
CREATE TABLE Users (
    user_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password CHAR(60) NOT NULL,
    nickname VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER',
    status VARCHAR(20) NOT NULL 
        CHECK (status IN ('active', 'inactive', 'banned', 'pending', 'deleted')),
    profile_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
);

-- Kanjis 테이블
CREATE TABLE Kanjis (
    kanji_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    jlpt_rank VARCHAR(10),
    category VARCHAR(20),
    kanji VARCHAR(4) NOT NULL,
    kor_onyomi VARCHAR(20),
    kor_kunyomi VARCHAR(20),
    jpn_onyomi VARCHAR(20),
    jpn_kunyomi VARCHAR(20),
    meaning VARCHAR(2000),
    PRIMARY KEY (kanji_id)
);

-- Stories 테이블
CREATE TABLE Stories (
    story_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    title VARCHAR(100),
    content TEXT,
    played_turns INT NOT NULL,
    is_ended BOOLEAN NOT NULL,
    thumbnail_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (story_id),
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- Community_Posts 테이블
CREATE TABLE Community_Posts (
    community_post_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    hit_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (community_post_id),
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- Shared_Stories 테이블
CREATE TABLE Shared_Stories (
    shared_story_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    story_id INT NOT NULL,
    hit_count INT NOT NULL DEFAULT 0,
    gaechu INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (shared_story_id),
    FOREIGN KEY (story_id) REFERENCES Stories(story_id) ON DELETE CASCADE
);

-- Kanji_Collections 테이블
CREATE TABLE Kanji_Collections (
    kanji_collection_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    kanji_id INT NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (kanji_collection_id),
    FOREIGN KEY (kanji_id) REFERENCES Kanjis(kanji_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- Community_Replies 테이블
CREATE TABLE Community_Replies (
    community_reply_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    community_post_id INT NOT NULL,
    user_id INT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (community_reply_id),
    FOREIGN KEY (community_post_id) REFERENCES Community_Posts(community_post_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- Used_Kanjis 테이블
CREATE TABLE Used_Kanjis (
    used_kanji_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    story_id INT NOT NULL,
    kanji_id INT NOT NULL,
    is_hint BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (used_kanji_id),
    FOREIGN KEY (story_id) REFERENCES Stories(story_id) ON DELETE CASCADE,
    FOREIGN KEY (kanji_id) REFERENCES Kanjis(kanji_id) ON DELETE CASCADE
);

-- Shared_Story_Replies 테이블
CREATE TABLE Shared_Story_Replies (
    community_reply_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    shared_story_id INT NOT NULL,
    user_id INT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (community_reply_id),
    FOREIGN KEY (shared_story_id) REFERENCES Shared_Stories(shared_story_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);


